version: '3'
services:
  site1:
    image: nginx:1.12
    container_name: site1
    volumes:
      - ./site1:/usr/share/nginx/html/
    expose:
      - "80"
    networks:
      - nginx

  site2:
    image: nginx:1.12
    container_name: site2
    volumes:
      - ./site2:/usr/share/nginx/html/
    expose:
      - "80"
    networks:
      - nginx

  reverse_proxy:
    build:
      context: ./reverse-proxy
    image: nginx:1.12
    container_name: proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./reverse-proxy/includes:/etc/nginx/includes
    ports:
      - "80:80"
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    driver: bridge
